---
resources:
  - name: tfl-app
    type: git
    source:
      uri: ((tfl.git_uri))
      branch: main

  - name: docker-registry
    type: docker-image
    source:
      repository: docker-registry:5000/tfl-app
      insecure_registries:
        - http://docker-registry:5000
      build_args:
        TFL_API_KEY: ((tfl.tfl_api_key))

jobs:
  - name: build-docker-image
    public: true
    serial: true
    plan:
      - get: tfl-app
        trigger: true
      - put: docker-registry
        params:
          build: tfl-app/app
